[build]
  command = "npx puppeteer browsers install chrome && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  PUPPETEER_CACHE_DIR = "/opt/build/repo/.netlify/plugins/puppeteer"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
